<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="System.Drawing.Common" Version="10.0.12" />
    <PackageVersion Include="McMaster.Extensions.CommandLineUtils" Version="5.1.0" />
    <PackageVersion Include="NAudio" Version="3.1.0" />
    <PackageVersion Include="NEST" Version="7.17.5" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
  </ItemGroup>
</Project>
