name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet restore SCI_Lib
        dotnet restore Tests
    - name: Build
      run: |
        dotnet build --no-restore SCI_Lib
        dotnet build --no-restore Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Directory.Build.props
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
