name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        dotnet restore SCI_Lib
        dotnet restore Tests
    - name: Build
      run: |
        dotnet build --no-restore SCI_Lib
        dotnet build --no-restore Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
          dotnet pack SCI_Lib -o out
          dotnet nuget push "out\*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate