name: deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [ master ]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore SCI_Lib
    - name: Build
      run: dotnet build --configuration Release --no-restore SCI_Lib
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: SCI_Lib/SCI_Lib.csproj
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
